status = [
  'unit-tests (3.9)',
  'unit-tests (3.10)',
  'unit-tests (3.11)',
  'integration-tests (3.9)',
  'integration-tests (3.10)',
  'integration-tests (3.11)',
  'linter',
  'image-build',
]
# 1 hour timeout
timeout-sec = 3600
