name: Run Docs Scraper

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Deployment?"
        default: "WhaTap"
  # schedule:
  # - cron: "30 9 * * *"
  # push:
  #   branches: 
  #     -main
  
jobs:
  cron:
    runs-on: ubuntu-20.04
    name: scraping docs
    steps:
      - uses: actions/checkout@v4
      - name: Run scraper
        env:
          HOST_URL: https://meilsearch.whatap.io
          API_KEY: dgoMBc2t6fVzILDGqhh63uBXACGOmJbKNnE_Xv8_Hqk
          CONFIG_FILE_PATH: ${{ github.workspace }}
        run: |
          docker run -t --rm \
            -e MEILISEARCH_HOST_URL=$HOST_URL \
            -e MEILISEARCH_API_KEY=$API_KEY \
            -v ${{ github.workspace }}/whatap-docs.json \
            getmeili/docs-scraper:latest pipenv run ./docs_scraper ./whatap-docs.json
